# Generated by Django 3.0.2 on 2020-01-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20200127_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
